/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MijnTicketsRouteImport } from './routes/mijn-tickets'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as BestellingOrderNumberRouteImport } from './routes/bestelling.$orderNumber'
import { Route as EvenementenIndexRouteImport } from './routes/evenementen.index'
import { Route as EvenementenSlugRouteImport } from './routes/evenementen.$slug'
import { Route as OrganisatorIndexRouteImport } from './routes/organisator.index'
import { Route as OrganisatorStartenRouteImport } from './routes/organisator.starten'
import { Route as TicketTicketNumberRouteImport } from './routes/ticket.$ticketNumber'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminEventsRouteImport } from './routes/_admin.admin.events'
import { Route as AdminAdminOrganizationsRouteImport } from './routes/_admin.admin.organizations'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events_.$eventId'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app.organization.index'
import { Route as AppOrganizationDetailsRouteImport } from './routes/_app.organization.details'
import { Route as AppOrganizationNotificationsRouteImport } from './routes/_app.organization.notifications'
import { Route as AppOrganizationPaymentsRouteImport } from './routes/_app.organization.payments'
import { Route as AppOrganizationSettingsRouteImport } from './routes/_app.organization.settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronEventRemindersRouteImport } from './routes/api/cron/event-reminders'
import { Route as ApiCronExpireOrdersRouteImport } from './routes/api/cron/expire-orders'
import { Route as EvenementenSlugAfrekenenRouteImport } from './routes/evenementen.$slug_.afrekenen'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app.events_.$eventId.index'
import { Route as AppEventsEventIdDetailsRouteImport } from './routes/_app.events_.$eventId.details'
import { Route as AppEventsEventIdOrdersRouteImport } from './routes/_app.events_.$eventId.orders'
import { Route as AppEventsEventIdReportsRouteImport } from './routes/_app.events_.$eventId.reports'
import { Route as AppEventsEventIdScannerRouteImport } from './routes/_app.events_.$eventId.scanner'
import { Route as AppEventsEventIdSettingsRouteImport } from './routes/_app.events_.$eventId.settings'
import { Route as AppEventsEventIdTicketsRouteImport } from './routes/_app.events_.$eventId.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MijnTicketsRoute = MijnTicketsRouteImport.update({
  id: '/mijn-tickets',
  path: '/mijn-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const BestellingOrderNumberRoute = BestellingOrderNumberRouteImport.update({
  id: '/bestelling/$orderNumber',
  path: '/bestelling/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenIndexRoute = EvenementenIndexRouteImport.update({
  id: '/evenementen/',
  path: '/evenementen/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenSlugRoute = EvenementenSlugRouteImport.update({
  id: '/evenementen/$slug',
  path: '/evenementen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisatorIndexRoute = OrganisatorIndexRouteImport.update({
  id: '/organisator/',
  path: '/organisator/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisatorStartenRoute = OrganisatorStartenRouteImport.update({
  id: '/organisator/starten',
  path: '/organisator/starten',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketNumberRoute = TicketTicketNumberRouteImport.update({
  id: '/ticket/$ticketNumber',
  path: '/ticket/$ticketNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEventsRoute = AdminAdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrganizationsRoute = AdminAdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationDetailsRoute = AppOrganizationDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationNotificationsRoute =
  AppOrganizationNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppOrganizationRoute,
  } as any)
const AppOrganizationPaymentsRoute = AppOrganizationPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationSettingsRoute = AppOrganizationSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEventRemindersRoute = ApiCronEventRemindersRouteImport.update({
  id: '/api/cron/event-reminders',
  path: '/api/cron/event-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExpireOrdersRoute = ApiCronExpireOrdersRouteImport.update({
  id: '/api/cron/expire-orders',
  path: '/api/cron/expire-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenSlugAfrekenenRoute =
  EvenementenSlugAfrekenenRouteImport.update({
    id: '/evenementen/$slug_/afrekenen',
    path: '/evenementen/$slug/afrekenen',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdDetailsRoute = AppEventsEventIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdOrdersRoute = AppEventsEventIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdReportsRoute = AppEventsEventIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdScannerRoute = AppEventsEventIdScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdSettingsRoute =
  AppEventsEventIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdTicketsRoute = AppEventsEventIdTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mijn-tickets': typeof MijnTicketsRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/organisator/starten': typeof OrganisatorStartenRoute
  '/ticket/$ticketNumber': typeof TicketTicketNumberRoute
  '/evenementen/': typeof EvenementenIndexRoute
  '/organisator/': typeof OrganisatorIndexRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/organizations': typeof AdminAdminOrganizationsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/events/new': typeof AppEventsNewRoute
  '/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/organization/details': typeof AppOrganizationDetailsRoute
  '/organization/notifications': typeof AppOrganizationNotificationsRoute
  '/organization/payments': typeof AppOrganizationPaymentsRoute
  '/organization/settings': typeof AppOrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/expire-orders': typeof ApiCronExpireOrdersRoute
  '/evenementen/$slug/afrekenen': typeof EvenementenSlugAfrekenenRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/events/$eventId/details': typeof AppEventsEventIdDetailsRoute
  '/events/$eventId/orders': typeof AppEventsEventIdOrdersRoute
  '/events/$eventId/reports': typeof AppEventsEventIdReportsRoute
  '/events/$eventId/scanner': typeof AppEventsEventIdScannerRoute
  '/events/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mijn-tickets': typeof MijnTicketsRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/organisator/starten': typeof OrganisatorStartenRoute
  '/ticket/$ticketNumber': typeof TicketTicketNumberRoute
  '/evenementen': typeof EvenementenIndexRoute
  '/organisator': typeof OrganisatorIndexRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/organizations': typeof AdminAdminOrganizationsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/events/new': typeof AppEventsNewRoute
  '/organization/details': typeof AppOrganizationDetailsRoute
  '/organization/notifications': typeof AppOrganizationNotificationsRoute
  '/organization/payments': typeof AppOrganizationPaymentsRoute
  '/organization/settings': typeof AppOrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/expire-orders': typeof ApiCronExpireOrdersRoute
  '/evenementen/$slug/afrekenen': typeof EvenementenSlugAfrekenenRoute
  '/admin': typeof AdminAdminIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/events/$eventId/details': typeof AppEventsEventIdDetailsRoute
  '/events/$eventId/orders': typeof AppEventsEventIdOrdersRoute
  '/events/$eventId/reports': typeof AppEventsEventIdReportsRoute
  '/events/$eventId/scanner': typeof AppEventsEventIdScannerRoute
  '/events/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/mijn-tickets': typeof MijnTicketsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/bestelling/$orderNumber': typeof BestellingOrderNumberRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/organisator/starten': typeof OrganisatorStartenRoute
  '/ticket/$ticketNumber': typeof TicketTicketNumberRoute
  '/evenementen/': typeof EvenementenIndexRoute
  '/organisator/': typeof OrganisatorIndexRoute
  '/_admin/admin/events': typeof AdminAdminEventsRoute
  '/_admin/admin/organizations': typeof AdminAdminOrganizationsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/events_/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/_app/organization/details': typeof AppOrganizationDetailsRoute
  '/_app/organization/notifications': typeof AppOrganizationNotificationsRoute
  '/_app/organization/payments': typeof AppOrganizationPaymentsRoute
  '/_app/organization/settings': typeof AppOrganizationSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/event-reminders': typeof ApiCronEventRemindersRoute
  '/api/cron/expire-orders': typeof ApiCronExpireOrdersRoute
  '/evenementen/$slug_/afrekenen': typeof EvenementenSlugAfrekenenRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/events_/$eventId/details': typeof AppEventsEventIdDetailsRoute
  '/_app/events_/$eventId/orders': typeof AppEventsEventIdOrdersRoute
  '/_app/events_/$eventId/reports': typeof AppEventsEventIdReportsRoute
  '/_app/events_/$eventId/scanner': typeof AppEventsEventIdScannerRoute
  '/_app/events_/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/_app/events_/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/_app/events_/$eventId/': typeof AppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mijn-tickets'
    | '/dashboard'
    | '/organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/bestelling/$orderNumber'
    | '/evenementen/$slug'
    | '/organisator/starten'
    | '/ticket/$ticketNumber'
    | '/evenementen/'
    | '/organisator/'
    | '/admin/events'
    | '/admin/organizations'
    | '/admin/users'
    | '/events/new'
    | '/events/$eventId'
    | '/organization/details'
    | '/organization/notifications'
    | '/organization/payments'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/cron/event-reminders'
    | '/api/cron/expire-orders'
    | '/evenementen/$slug/afrekenen'
    | '/admin/'
    | '/events/'
    | '/organization/'
    | '/events/$eventId/details'
    | '/events/$eventId/orders'
    | '/events/$eventId/reports'
    | '/events/$eventId/scanner'
    | '/events/$eventId/settings'
    | '/events/$eventId/tickets'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mijn-tickets'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/bestelling/$orderNumber'
    | '/evenementen/$slug'
    | '/organisator/starten'
    | '/ticket/$ticketNumber'
    | '/evenementen'
    | '/organisator'
    | '/admin/events'
    | '/admin/organizations'
    | '/admin/users'
    | '/events/new'
    | '/organization/details'
    | '/organization/notifications'
    | '/organization/payments'
    | '/organization/settings'
    | '/api/auth/$'
    | '/api/cron/event-reminders'
    | '/api/cron/expire-orders'
    | '/evenementen/$slug/afrekenen'
    | '/admin'
    | '/events'
    | '/organization'
    | '/events/$eventId/details'
    | '/events/$eventId/orders'
    | '/events/$eventId/reports'
    | '/events/$eventId/scanner'
    | '/events/$eventId/settings'
    | '/events/$eventId/tickets'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/mijn-tickets'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/bestelling/$orderNumber'
    | '/evenementen/$slug'
    | '/organisator/starten'
    | '/ticket/$ticketNumber'
    | '/evenementen/'
    | '/organisator/'
    | '/_admin/admin/events'
    | '/_admin/admin/organizations'
    | '/_admin/admin/users'
    | '/_app/events/new'
    | '/_app/events_/$eventId'
    | '/_app/organization/details'
    | '/_app/organization/notifications'
    | '/_app/organization/payments'
    | '/_app/organization/settings'
    | '/api/auth/$'
    | '/api/cron/event-reminders'
    | '/api/cron/expire-orders'
    | '/evenementen/$slug_/afrekenen'
    | '/_admin/admin/'
    | '/_app/events/'
    | '/_app/organization/'
    | '/_app/events_/$eventId/details'
    | '/_app/events_/$eventId/orders'
    | '/_app/events_/$eventId/reports'
    | '/_app/events_/$eventId/scanner'
    | '/_app/events_/$eventId/settings'
    | '/_app/events_/$eventId/tickets'
    | '/_app/events_/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MijnTicketsRoute: typeof MijnTicketsRoute
  BestellingOrderNumberRoute: typeof BestellingOrderNumberRoute
  EvenementenSlugRoute: typeof EvenementenSlugRoute
  OrganisatorStartenRoute: typeof OrganisatorStartenRoute
  TicketTicketNumberRoute: typeof TicketTicketNumberRoute
  EvenementenIndexRoute: typeof EvenementenIndexRoute
  OrganisatorIndexRoute: typeof OrganisatorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronEventRemindersRoute: typeof ApiCronEventRemindersRoute
  ApiCronExpireOrdersRoute: typeof ApiCronExpireOrdersRoute
  EvenementenSlugAfrekenenRoute: typeof EvenementenSlugAfrekenenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijn-tickets': {
      id: '/mijn-tickets'
      path: '/mijn-tickets'
      fullPath: '/mijn-tickets'
      preLoaderRoute: typeof MijnTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/bestelling/$orderNumber': {
      id: '/bestelling/$orderNumber'
      path: '/bestelling/$orderNumber'
      fullPath: '/bestelling/$orderNumber'
      preLoaderRoute: typeof BestellingOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/': {
      id: '/evenementen/'
      path: '/evenementen'
      fullPath: '/evenementen/'
      preLoaderRoute: typeof EvenementenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/$slug': {
      id: '/evenementen/$slug'
      path: '/evenementen/$slug'
      fullPath: '/evenementen/$slug'
      preLoaderRoute: typeof EvenementenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisator/': {
      id: '/organisator/'
      path: '/organisator'
      fullPath: '/organisator/'
      preLoaderRoute: typeof OrganisatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisator/starten': {
      id: '/organisator/starten'
      path: '/organisator/starten'
      fullPath: '/organisator/starten'
      preLoaderRoute: typeof OrganisatorStartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketNumber': {
      id: '/ticket/$ticketNumber'
      path: '/ticket/$ticketNumber'
      fullPath: '/ticket/$ticketNumber'
      preLoaderRoute: typeof TicketTicketNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/events': {
      id: '/_admin/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/organizations': {
      id: '/_admin/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminAdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events_/$eventId': {
      id: '/_app/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/details': {
      id: '/_app/organization/details'
      path: '/details'
      fullPath: '/organization/details'
      preLoaderRoute: typeof AppOrganizationDetailsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/notifications': {
      id: '/_app/organization/notifications'
      path: '/notifications'
      fullPath: '/organization/notifications'
      preLoaderRoute: typeof AppOrganizationNotificationsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/payments': {
      id: '/_app/organization/payments'
      path: '/payments'
      fullPath: '/organization/payments'
      preLoaderRoute: typeof AppOrganizationPaymentsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/settings': {
      id: '/_app/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof AppOrganizationSettingsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/event-reminders': {
      id: '/api/cron/event-reminders'
      path: '/api/cron/event-reminders'
      fullPath: '/api/cron/event-reminders'
      preLoaderRoute: typeof ApiCronEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire-orders': {
      id: '/api/cron/expire-orders'
      path: '/api/cron/expire-orders'
      fullPath: '/api/cron/expire-orders'
      preLoaderRoute: typeof ApiCronExpireOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/$slug_/afrekenen': {
      id: '/evenementen/$slug_/afrekenen'
      path: '/evenementen/$slug/afrekenen'
      fullPath: '/evenementen/$slug/afrekenen'
      preLoaderRoute: typeof EvenementenSlugAfrekenenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events_/$eventId/': {
      id: '/_app/events_/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/details': {
      id: '/_app/events_/$eventId/details'
      path: '/details'
      fullPath: '/events/$eventId/details'
      preLoaderRoute: typeof AppEventsEventIdDetailsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/orders': {
      id: '/_app/events_/$eventId/orders'
      path: '/orders'
      fullPath: '/events/$eventId/orders'
      preLoaderRoute: typeof AppEventsEventIdOrdersRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/reports': {
      id: '/_app/events_/$eventId/reports'
      path: '/reports'
      fullPath: '/events/$eventId/reports'
      preLoaderRoute: typeof AppEventsEventIdReportsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/scanner': {
      id: '/_app/events_/$eventId/scanner'
      path: '/scanner'
      fullPath: '/events/$eventId/scanner'
      preLoaderRoute: typeof AppEventsEventIdScannerRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/settings': {
      id: '/_app/events_/$eventId/settings'
      path: '/settings'
      fullPath: '/events/$eventId/settings'
      preLoaderRoute: typeof AppEventsEventIdSettingsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/tickets': {
      id: '/_app/events_/$eventId/tickets'
      path: '/tickets'
      fullPath: '/events/$eventId/tickets'
      preLoaderRoute: typeof AppEventsEventIdTicketsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminEventsRoute: typeof AdminAdminEventsRoute
  AdminAdminOrganizationsRoute: typeof AdminAdminOrganizationsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminEventsRoute: AdminAdminEventsRoute,
  AdminAdminOrganizationsRoute: AdminAdminOrganizationsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrganizationRouteChildren {
  AppOrganizationDetailsRoute: typeof AppOrganizationDetailsRoute
  AppOrganizationNotificationsRoute: typeof AppOrganizationNotificationsRoute
  AppOrganizationPaymentsRoute: typeof AppOrganizationPaymentsRoute
  AppOrganizationSettingsRoute: typeof AppOrganizationSettingsRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationDetailsRoute: AppOrganizationDetailsRoute,
  AppOrganizationNotificationsRoute: AppOrganizationNotificationsRoute,
  AppOrganizationPaymentsRoute: AppOrganizationPaymentsRoute,
  AppOrganizationSettingsRoute: AppOrganizationSettingsRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdDetailsRoute: typeof AppEventsEventIdDetailsRoute
  AppEventsEventIdOrdersRoute: typeof AppEventsEventIdOrdersRoute
  AppEventsEventIdReportsRoute: typeof AppEventsEventIdReportsRoute
  AppEventsEventIdScannerRoute: typeof AppEventsEventIdScannerRoute
  AppEventsEventIdSettingsRoute: typeof AppEventsEventIdSettingsRoute
  AppEventsEventIdTicketsRoute: typeof AppEventsEventIdTicketsRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdDetailsRoute: AppEventsEventIdDetailsRoute,
  AppEventsEventIdOrdersRoute: AppEventsEventIdOrdersRoute,
  AppEventsEventIdReportsRoute: AppEventsEventIdReportsRoute,
  AppEventsEventIdScannerRoute: AppEventsEventIdScannerRoute,
  AppEventsEventIdSettingsRoute: AppEventsEventIdSettingsRoute,
  AppEventsEventIdTicketsRoute: AppEventsEventIdTicketsRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MijnTicketsRoute: MijnTicketsRoute,
  BestellingOrderNumberRoute: BestellingOrderNumberRoute,
  EvenementenSlugRoute: EvenementenSlugRoute,
  OrganisatorStartenRoute: OrganisatorStartenRoute,
  TicketTicketNumberRoute: TicketTicketNumberRoute,
  EvenementenIndexRoute: EvenementenIndexRoute,
  OrganisatorIndexRoute: OrganisatorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronEventRemindersRoute: ApiCronEventRemindersRoute,
  ApiCronExpireOrdersRoute: ApiCronExpireOrdersRoute,
  EvenementenSlugAfrekenenRoute: EvenementenSlugAfrekenenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
