/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppOrganizationRouteImport } from './routes/_app.organization'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as EvenementenIndexRouteImport } from './routes/evenementen.index'
import { Route as EvenementenSlugRouteImport } from './routes/evenementen.$slug'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppEventsNewRouteImport } from './routes/_app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events_.$eventId'
import { Route as AppOrganizationIndexRouteImport } from './routes/_app.organization.index'
import { Route as AppOrganizationBrandingRouteImport } from './routes/_app.organization.branding'
import { Route as AppOrganizationGeneralRouteImport } from './routes/_app.organization.general'
import { Route as AppOrganizationPaymentsRouteImport } from './routes/_app.organization.payments'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app.events_.$eventId.index'
import { Route as AppEventsEventIdContentRouteImport } from './routes/_app.events_.$eventId.content'
import { Route as AppEventsEventIdSettingsRouteImport } from './routes/_app.events_.$eventId.settings'
import { Route as AppEventsEventIdTicketsRouteImport } from './routes/_app.events_.$eventId.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const EvenementenIndexRoute = EvenementenIndexRouteImport.update({
  id: '/evenementen/',
  path: '/evenementen/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementenSlugRoute = EvenementenSlugRouteImport.update({
  id: '/evenementen/$slug',
  path: '/evenementen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationIndexRoute = AppOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationBrandingRoute = AppOrganizationBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationGeneralRoute = AppOrganizationGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const AppOrganizationPaymentsRoute = AppOrganizationPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppOrganizationRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdContentRoute = AppEventsEventIdContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdSettingsRoute =
  AppEventsEventIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdTicketsRoute = AppEventsEventIdTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/evenementen/': typeof EvenementenIndexRoute
  '/events/new': typeof AppEventsNewRoute
  '/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/organization/branding': typeof AppOrganizationBrandingRoute
  '/organization/general': typeof AppOrganizationGeneralRoute
  '/organization/payments': typeof AppOrganizationPaymentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/': typeof AppEventsIndexRoute
  '/organization/': typeof AppOrganizationIndexRoute
  '/events/$eventId/content': typeof AppEventsEventIdContentRoute
  '/events/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/evenementen': typeof EvenementenIndexRoute
  '/events/new': typeof AppEventsNewRoute
  '/organization/branding': typeof AppOrganizationBrandingRoute
  '/organization/general': typeof AppOrganizationGeneralRoute
  '/organization/payments': typeof AppOrganizationPaymentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events': typeof AppEventsIndexRoute
  '/organization': typeof AppOrganizationIndexRoute
  '/events/$eventId/content': typeof AppEventsEventIdContentRoute
  '/events/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/evenementen/$slug': typeof EvenementenSlugRoute
  '/evenementen/': typeof EvenementenIndexRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/events_/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/_app/organization/branding': typeof AppOrganizationBrandingRoute
  '/_app/organization/general': typeof AppOrganizationGeneralRoute
  '/_app/organization/payments': typeof AppOrganizationPaymentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/organization/': typeof AppOrganizationIndexRoute
  '/_app/events_/$eventId/content': typeof AppEventsEventIdContentRoute
  '/_app/events_/$eventId/settings': typeof AppEventsEventIdSettingsRoute
  '/_app/events_/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
  '/_app/events_/$eventId/': typeof AppEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/evenementen/$slug'
    | '/evenementen/'
    | '/events/new'
    | '/events/$eventId'
    | '/organization/branding'
    | '/organization/general'
    | '/organization/payments'
    | '/api/auth/$'
    | '/events/'
    | '/organization/'
    | '/events/$eventId/content'
    | '/events/$eventId/settings'
    | '/events/$eventId/tickets'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/evenementen/$slug'
    | '/evenementen'
    | '/events/new'
    | '/organization/branding'
    | '/organization/general'
    | '/organization/payments'
    | '/api/auth/$'
    | '/events'
    | '/organization'
    | '/events/$eventId/content'
    | '/events/$eventId/settings'
    | '/events/$eventId/tickets'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/evenementen/$slug'
    | '/evenementen/'
    | '/_app/events/new'
    | '/_app/events_/$eventId'
    | '/_app/organization/branding'
    | '/_app/organization/general'
    | '/_app/organization/payments'
    | '/api/auth/$'
    | '/_app/events/'
    | '/_app/organization/'
    | '/_app/events_/$eventId/content'
    | '/_app/events_/$eventId/settings'
    | '/_app/events_/$eventId/tickets'
    | '/_app/events_/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  EvenementenSlugRoute: typeof EvenementenSlugRoute
  EvenementenIndexRoute: typeof EvenementenIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/evenementen/': {
      id: '/evenementen/'
      path: '/evenementen'
      fullPath: '/evenementen/'
      preLoaderRoute: typeof EvenementenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementen/$slug': {
      id: '/evenementen/$slug'
      path: '/evenementen/$slug'
      fullPath: '/evenementen/$slug'
      preLoaderRoute: typeof EvenementenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events_/$eventId': {
      id: '/_app/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization/': {
      id: '/_app/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AppOrganizationIndexRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/branding': {
      id: '/_app/organization/branding'
      path: '/branding'
      fullPath: '/organization/branding'
      preLoaderRoute: typeof AppOrganizationBrandingRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/general': {
      id: '/_app/organization/general'
      path: '/general'
      fullPath: '/organization/general'
      preLoaderRoute: typeof AppOrganizationGeneralRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/_app/organization/payments': {
      id: '/_app/organization/payments'
      path: '/payments'
      fullPath: '/organization/payments'
      preLoaderRoute: typeof AppOrganizationPaymentsRouteImport
      parentRoute: typeof AppOrganizationRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events_/$eventId/': {
      id: '/_app/events_/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/content': {
      id: '/_app/events_/$eventId/content'
      path: '/content'
      fullPath: '/events/$eventId/content'
      preLoaderRoute: typeof AppEventsEventIdContentRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/settings': {
      id: '/_app/events_/$eventId/settings'
      path: '/settings'
      fullPath: '/events/$eventId/settings'
      preLoaderRoute: typeof AppEventsEventIdSettingsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/_app/events_/$eventId/tickets': {
      id: '/_app/events_/$eventId/tickets'
      path: '/tickets'
      fullPath: '/events/$eventId/tickets'
      preLoaderRoute: typeof AppEventsEventIdTicketsRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppOrganizationRouteChildren {
  AppOrganizationBrandingRoute: typeof AppOrganizationBrandingRoute
  AppOrganizationGeneralRoute: typeof AppOrganizationGeneralRoute
  AppOrganizationPaymentsRoute: typeof AppOrganizationPaymentsRoute
  AppOrganizationIndexRoute: typeof AppOrganizationIndexRoute
}

const AppOrganizationRouteChildren: AppOrganizationRouteChildren = {
  AppOrganizationBrandingRoute: AppOrganizationBrandingRoute,
  AppOrganizationGeneralRoute: AppOrganizationGeneralRoute,
  AppOrganizationPaymentsRoute: AppOrganizationPaymentsRoute,
  AppOrganizationIndexRoute: AppOrganizationIndexRoute,
}

const AppOrganizationRouteWithChildren = AppOrganizationRoute._addFileChildren(
  AppOrganizationRouteChildren,
)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdContentRoute: typeof AppEventsEventIdContentRoute
  AppEventsEventIdSettingsRoute: typeof AppEventsEventIdSettingsRoute
  AppEventsEventIdTicketsRoute: typeof AppEventsEventIdTicketsRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdContentRoute: AppEventsEventIdContentRoute,
  AppEventsEventIdSettingsRoute: AppEventsEventIdSettingsRoute,
  AppEventsEventIdTicketsRoute: AppEventsEventIdTicketsRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  EvenementenSlugRoute: EvenementenSlugRoute,
  EvenementenIndexRoute: EvenementenIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
